Models/BlogPost.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace codemaiden.info.Models
{
	public class BlogPost
	{
		[Key]
		public int BlogPostId { get; set; }

		public string Title { get; set; }

		[Column(TypeName = "ntext")]
		[MaxLength]
		public string Body { get; set; }
	}
}

Models/UserProfile.cs
using System.ComponentModel.DataAnnotations;

namespace codemaiden.info.Models
{
	public class UserProfile
	{
		public const string SessionKey = "UserProfile";

		[Key]
		public string AuthId { get; set; }

		public string DisplayName { get; set; }
		public bool IsSysOp { get; set; }
	}
}

ViewModels/AccountWelcomeViewModel.cs
using System.Collections.Generic;

namespace codemaiden.info.ViewModels
{
	public class AccountWelcomeViewModel
	{
		public List<string> Errors { get; set; }
	}
}

ViewModels/BlogIndexViewModel.cs
using System.Collections.Generic;
using codemaiden.info.Models;

namespace codemaiden.info.ViewModels
{
	public class BlogIndexViewModel
	{
		public BlogIndexViewModel(IEnumerable<BlogPost> blogPosts)
		{
			BlogPosts = blogPosts;
		}

		public IEnumerable<BlogPost> BlogPosts { get; set; }
	}
}

ViewModels/CourseEditModel.cs
//using System.ComponentModel.DataAnnotations;
//
//namespace codemaiden.info.ViewModels
//{
//	public class CourseEditModel
//	{
//		public CourseEditModel() { }
//
//		public CourseEditModel(Course course) {
//			Id = course.Id;
//			Name = course.Name;
//			Subject = course.Subject;
//		}
//
//		[Required] public int Id { get; set; }
//
//		[Required] [MaxLength(80)] public string Name { get; set; }
//
//		[Required] public Subject Subject { get; set; }
//	}
//}

ViewModels/HomeIndexViewModel.cs
namespace codemaiden.info.ViewModels
{
	public class HomeIndexViewModel
	{
	}
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace codemaiden.info.Controllers
{
	public class AboutController : Controller
	{
		public IActionResult Phone()
		{
			return Content("Hi i am phone!");
		}

		public string Meow()
		{
			return "meow";
		}
	}
}

Controllers/AccountController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using codemaiden.info.Extensions;
using codemaiden.info.FormDataModels;
using codemaiden.info.Models;
using codemaiden.info.Services;
using codemaiden.info.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace codemaiden.info.Controllers
{
	public class AccountController : Controller
	{
		private IProfileStore _profileStore;

		public AccountController(IProfileStore profileStore)
		{
			_profileStore = profileStore;
		}

		[HttpGet]
		public IActionResult AccessDenied(string returnUrl)
		{
			return View("AccessDenied", returnUrl);
		}

		[HttpGet]
		public async Task Login(string returnUrl = "/")
		{
			await HttpContext.ChallengeAsync("Auth0", new AuthenticationProperties
			{
				RedirectUri = returnUrl
			});
		}

		// TODO make this POST
		[Authorize]
		[HttpGet]
		public async Task Logout()
		{
			await HttpContext.SignOutAsync("Auth0", new AuthenticationProperties
			{
				RedirectUri = Url.Action("Return")
			});
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
		}

		public IActionResult Return()
		{
			return RedirectToAction("Index", "Home");
		}

		[Authorize]
		public IActionResult Claims()
		{
			var claims = User.Claims.ToList();
			var id = User.GetNameId();
			return View(new UserProfileViewModel
			{
				Name = User.Identity.Name,
				EmailAddress = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value,
				ProfileImage = User.Claims.FirstOrDefault(c => c.Type == "picture")?.Value,
				CmUserProfile = HttpContext.Items[UserProfile.SessionKey] as UserProfile
			});
		}

		[Authorize(Policy = "IsSysOp")]
		public IActionResult PuddingKingdom()
		{
			return Content("Welcome to the pudding kingdom!!!");
		}

		[Authorize(Roles = "admin")]
		public IActionResult Admin()
		{
			return Content("Hello, admin!");
		}

		[Authorize]
		public IActionResult Welcome()
		{
			var errors = new List<string>();
			if (Request.Cookies.TryGetValue("FlashErrors", out var errorString))
			{
				errors.AddRange(errorString.Split(';').Select(error => error.FromBase64()));
				Response.Cookies.Delete("FlashErrors");
			}

			var vm = new AccountWelcomeViewModel
			{
				Errors = errors
			};
			return View(vm);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult CreateProfile(CreateProfileDataModel model)
		{
			if (!ModelState.IsValid)
			{
				var errors = new List<string>();
				foreach (var state in ModelState.Values)
				{
					foreach (var error in state.Errors) errors.Add(error.ErrorMessage.ToBase64());
				}

				Response.Cookies.Append("FlashErrors", errors.Aggregate((x, y) => $"{x};{y}"));
				return RedirectToAction("Welcome");
			}

			_profileStore.CreateProfile(new UserProfile
			{
				AuthId = User.GetNameId(),
				DisplayName = model.DisplayName,
				IsSysOp = false
			});
			return RedirectToAction("Claims");
		}
	}

	public class UserProfileViewModel
	{
		public string Name { get; set; }
		public string EmailAddress { get; set; }
		public string ProfileImage { get; set; }
		public UserProfile CmUserProfile { get; set; }
	}
}

Controllers/BlogController.cs
using codemaiden.info.Services;
using codemaiden.info.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace codemaiden.info.Controllers
{
	public class BlogController : Controller
	{
		private readonly IBlogData _blogPosts;

		public BlogController(IBlogData blogPosts)
		{
			_blogPosts = blogPosts;
		}

		public IActionResult Index()
		{
			return View(new BlogIndexViewModel(_blogPosts.AllBlogPosts()));
		}
	}
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace codemaiden.info.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

//		[HttpGet]
//		public IActionResult Index() {
//			var vm = new HomeIndexViewModel {
//				Courses = _courseData.FetchAll(),
//				CurrentMessage = _greeter.GetMessageOfTheDay()
//			};
//
//			return View(vm);
//		}
//
//		[HttpGet]
//		public IActionResult Details(int id) {
//			var course = _courseData.Fetch(id);
//			if (course == null) return NotFound();
//
//			return View(course);
//		}
//
//		[HttpGet]
//		[Authorize]
//		public IActionResult Create() {
//			return View();
//		}
//
//		[HttpPost]
//		[ValidateAntiForgeryToken]
//		[Authorize]
//		public IActionResult Create(CourseEditModel model) {
//			if (!ModelState.IsValid) return View();
//
//			if (model.Id != 0) return StatusCode(500);
//
//			var course = new Course {
//				Name = model.Name,
//				Subject = model.Subject
//			};
//
//			course = _courseData.Add(course);
//
//			return RedirectToAction(nameof(Details), new {id = course.Id});
//		}
//
//		[HttpGet]
//		[Authorize]
//		public IActionResult Edit(int id) {
//			var course = _courseData.Fetch(id);
//			if (course == null) return NotFound();
//
//			return View(new CourseEditModel(course));
//		}
//
//		[HttpPost]
//		[ValidateAntiForgeryToken]
//		[Authorize]
//		public IActionResult Edit(CourseEditModel model) {
//			if (!ModelState.IsValid) return View(model);
//
//			var course = _courseData.Fetch(model.Id);
//			if (course == null) return NotFound();
//
//			course.Name = model.Name;
//			course.Subject = model.Subject;
//
//			_courseData.Update(course);
//
//			return RedirectToAction(nameof(Details), new {id = course.Id});
//		}
	}
}

ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace codemaiden.info.ViewComponents
{
	public class GreeterViewComponent : ViewComponent
	{
		private readonly IGreeter _greeter;

		public GreeterViewComponent(IGreeter greeter)
		{
			_greeter = greeter;
		}

		public IViewComponentResult Invoke()
		{
			var model = _greeter.GetMessageOfTheDay();
			return View("Default", model);
		}
	}
}

Views/Blog/Index.cshtml
@model BlogIndexViewModel

@{
	ViewBag.Title = "Blog Posts";
}

<div class="row">
	<div class="col-12">
		<h1>Blog Posts</h1>
		<hr/>
		@foreach (var blogPost in Model.BlogPosts)
		{
			<div class="card">
				<h5 class="card-header">@blogPost.Title</h5>
				<div class="card-body">
					@*					<h5 class="card-title">Special title treatment</h5>*@
					<p class="card-text">@Html.Raw(blogPost.Body)</p>
					@*					<a href="#" class="btn btn-primary">Go somewhere</a>*@
				</div>
			</div>
		}
	</div>
</div>

Views/Home/Create.cshtml
@model Course

@{
	ViewBag.Title = "Create Course";
}

<h1>Create Course</h1>
<form method="POST">
	<div>
		<label asp-for="Name"></label>
		<input type="text" asp-for="Name"/>
		<span asp-validation-for="Name"></span>
	</div>
	<div>
		<label asp-for="Subject"></label>
		<select asp-for="Subject" asp-items="@(Html.GetEnumSelectList<Subject>())"></select>
		<span asp-validation-for="Subject"></span>
	</div>
	<input type="submit" name="save" value="Save"/>
</form>

Views/Home/Details.cshtml
@model Course

@{
	ViewBag.Title = $"Viewing {Model.Name}";
}

<h1>Id: @Model.Id</h1>
<h1>Name: @Model.Name</h1>
<h1>Subject: @Model.Subject</h1>

Views/Home/Edit.cshtml
@model CourseEditModel

@{
	ViewBag.Title = $"Editing {Model.Name}";
}

<h1>Editing @Model.Name</h1>
<form method="POST" class="needs-validation" novalidate>
	<input type="hidden" asp-for="Id"/>
	<div class="form-group">
		<label asp-for="Name"></label>
		<input type="text" asp-for="Name" class="form-control"/>
		<span class="invalid-feedback" asp-validation-for="Name"></span>
	</div>

	<div class="form-group">
		<label asp-for="Subject"></label>
		<select asp-for="Subject" asp-items="@(Html.GetEnumSelectList<Subject>())" class="form-control"></select>
		<span asp-validation-for="Subject"></span>
	</div>

	<input type="submit" name="save" value="Save" class="btn btn-primary"/>
</form>

@section FooterJS {
}

Views/Home/Index.cshtml
@model HomeIndexViewModel
@{
	ViewBag.Title = "Course Index";
}

<div class="row">
	<div class="col-12">
		<h1>Welcome Home</h1>
		<hr/>
		@if (User.Identity.IsAuthenticated)
		{
			<h2>You are <strong>signed in</strong>.</h2>
			<a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Logout</a>
		}
		else
		{
			<h2>You are <strong>not signed in</strong>.</h2>
			<a asp-controller="Account" asp-action="Login" class="btn btn-success">Login</a>
		}
	</div>
</div>

Views/Home/Partials/_Summary.cshtml
@model Course

<div class="card">
	<div class="card-body">
		<h5 class="card-title">@Model.Name</h5>
		<h6 class="card-subtitle mb-2 text-muted">Course Id: @Model.Id</h6>
		<p class="card-text">This course is part of the @Model.Subject subject.</p>
		<a asp-action="Details" asp-route-id="@Model.Id" class="card-link">View</a>
		<a asp-action="Edit" asp-route-id="@Model.Id" class="card-link">Edit</a>
	</div>
</div>

Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>
	@Model
</div>

Views/Shared/_Layout.cshtml
@using codemaiden.info.Extensions
<!DOCTYPE html>
<html>
<head>
	<title>@ViewBag.Title</title>
	<link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<style type="text/css">
		.invalid-feedback.field-validation-error { display: inherit; }
	</style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="#">Codemaiden</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav">
			<li class="nav-item active">
				<a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" asp-controller="Blog" asp-action="Index">Blog</a>
			</li>
			@if (User.Identity.IsAuthenticated && Context.GetProfile().IsSysOp)
			{
				<li class="nav-item">
					<a class="nav-link" asp-controller="Account" asp-action="PuddingKingdom">Secret Pudding Kingdom</a>
				</li>
			}
		</ul>
	</div>
</nav>

<div>
	<div class="container">
		@RenderBody()
	</div>
</div>
<footer>
	<hr/>
	@RenderSection("Footer", false)
	@*    <vc:Greeter></vc:Greeter>*@
</footer>

<script type="text/javascript" src="~/node_modules/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="~/node_modules/popper.js/dist/umd/popper.min.js"></script>
<script type="text/javascript" src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="~/node_modules/jquery-validation/dist/jquery.validate.min.js"></script>

<script type="text/javascript">
	$.validator.unobtrusive = {};
	$.validator.unobtrusive.options = {
		errorClass: 'invalid',
		validClass: 'valid'
	};
</script>

<script type="text/javascript" src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
@RenderSection("FooterJS", false)
</body>
</html>